Traceback (most recent call last):
  File "main.py", line 127, in <module>
    managerial_layer()
  File "main.py", line 123, in managerial_layer
    unfold_network(cpc_time_series, tensors, topical_patents[:2]) 
  File "/cluster/raid/home/michael.tsesmelis/SideProject/network_analysis.py", line 156, in unfold_network
    assignee_df = assignee_index(topical_assignees, tensors["assignee"])
  File "/cluster/raid/home/michael.tsesmelis/SideProject/network_analysis.py", line 73, in assignee_index
    assignees_df['name'] = assignees_df['ID'].apply(lambda x: tensor_assignee[x]['organisation'])
  File "/cluster/raid/home/michael.tsesmelis/SideProject/lib/python3.8/site-packages/pandas/core/series.py", line 4357, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/cluster/raid/home/michael.tsesmelis/SideProject/lib/python3.8/site-packages/pandas/core/apply.py", line 1043, in apply
    return self.apply_standard()
  File "/cluster/raid/home/michael.tsesmelis/SideProject/lib/python3.8/site-packages/pandas/core/apply.py", line 1098, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2859, in pandas._libs.lib.map_infer
  File "/cluster/raid/home/michael.tsesmelis/SideProject/network_analysis.py", line 73, in <lambda>
    assignees_df['name'] = assignees_df['ID'].apply(lambda x: tensor_assignee[x]['organisation'])
TypeError: string indices must be integers
