Traceback (most recent call last):
  File "main.py", line 127, in <module>
  File "main.py", line 123, in managerial_layer
    
  File "/cluster/raid/home/michael.tsesmelis/SideProject/network_analysis.py", line 159, in unfold_network
    assignee_df = network_indices(cpc_nodes, assignee_nodes, edges, assignee_df)
  File "/cluster/raid/home/michael.tsesmelis/SideProject/network_analysis.py", line 114, in network_indices
    impact, length = impact_index(node, network)
  File "/cluster/raid/home/michael.tsesmelis/SideProject/network_analysis.py", line 84, in impact_index
    print(node, network[node], network.neighbours(node))
  File "/cluster/raid/home/michael.tsesmelis/SideProject/lib/python3.8/site-packages/networkx/classes/graph.py", line 476, in __getitem__
    return self.adj[n]
  File "/cluster/raid/home/michael.tsesmelis/SideProject/lib/python3.8/site-packages/networkx/classes/coreviews.py", line 82, in __getitem__
    return AtlasView(self._atlas[name])
TypeError: unhashable type: 'dict'
