Traceback (most recent call last):
  File "data_preprocessing.py", line 150, in <module>
    df = data_preparation(categories, period_start, period_end)
  File "data_preprocessing.py", line 142, in data_preparation
    cluster_complete = fill_dataframe(category, tensors, cluster)
  File "data_preprocessing.py", line 87, in fill_dataframe
    le.fit(cpc_to_labels)
  File "/cluster/raid/home/michael.tsesmelis/SideProject/lib/python3.8/site-packages/sklearn/preprocessing/_label.py", line 98, in fit
    y = column_or_1d(y, warn=True)
  File "/cluster/raid/home/michael.tsesmelis/SideProject/lib/python3.8/site-packages/sklearn/utils/validation.py", line 1038, in column_or_1d
    raise ValueError(
ValueError: y should be a 1d array, got an array of shape () instead.
